project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!logo.qmd"
    - "!format_data/"

website:
  title: "EclipsaR"
  navbar:
    background: transparent
    left:
      - href: index.qmd
        text: Home
      - href: Map_21st_century_eclipses.qmd
        text: 21st century eclipses
      - href: interactive_table.qmd
        text: Eclipse info
      - href: fun_facts.qmd
        text: Fun facts
      - href: individual_examples.qmd
        text: Eclipse examples
  page-footer:
    center:
      - href: about.qmd
        text: about us
    background: transparent
    foreground: white


format:
  html:
    theme: [cosmo, brand]

execute:
  echo: false
  warning: false
  freeze: auto