---
title: "Eclipses by country"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
library(plotly)
```

```{r}
#Get eclipse data
eclipse_data <- read_csv("data/formatted_eclipses.csv")
```

```{r}
#Get list of countries
world <- ne_countries(
  scale = "medium",
  returnclass = "sf"
)
```

```{r}
#Create object countries from country name and code in object world
country_lookup <- world %>%
  st_drop_geometry() %>%
  select(
    country = name,
    iso_a3
  ) %>%
  distinct()
```

```{r}
#Replace country name abbreviations
country_name_replacements <- c(
  "Marshall Is." = "Marshall Islands",
  "N. Mariana Is." = "Northern Mariana Islands",
  "U.S. Virgin Is." = "United States Virgin Islands",
  "S. Geo. and the Is." = "South Georgia and the South Sandwich Islands",
  "Br. Indian Ocean Ter." = "British Indian Ocean Territory",
  "Pitcairn Is." = "Pitcairn Islands",
  "Falkland Is." = "Falkland Islands",
  "Cayman Is." = "Cayman Islands",
  "British Virgin Is." = "British Virgin Islands",
  "Turks and Caicos Is." = "Turks and Caicos Islands",
  "S. Sudan" = "South Sudan",
  "Solomon Is." = "Solomon Islands",
  "St. Vin. and Gren." = "Saint Vincent and the Grenadines",
  "St. Kitts and Nevis" = "Saint Kitts and Nevis",
  "Cook Is." = "Cook Islands",
  "W. Sahara" = "Western Sahara",
  "St. Pierre and Miquelon" = "Saint Pierre and Miquelon",
  "Wallis and Futuna Is." = "Wallis and Futuna",
  "Fr. Polynesia" = "French Polynesia",
  "Fr. S. Antarctic Lands" = "French Southern Territories",
  "Eq. Guinea" = "Equatorial Guinea",
  "Dominican Rep." = "Dominican Republic",
  "Faeroe Is." = "Faroe Islands",
  "N. Cyprus" = "Northern Cyprus",
  "Dem. Rep. Congo" = "Democratic Republic of the Congo",
  "Central African Rep." = "Central African Republic",
  "Bosnia and Herz." = "Bosnia and Herzegovina",
  "Indian Ocean Ter." = "Indian Ocean Territories",
  "Heard I. and McDonald Is." = "Heard Island and McDonald Islands",
  "Ashmore and Cartier Is." = "Ashmore and Cartier Islands",
  "Antigua and Barb." = "Antigua and Barbuda"
)

country_lookup <- country_lookup %>%
  mutate(
    country = recode(
      country,
      !!!country_name_replacements
    )
  )
```


```{r}
states <- ne_states(
  returnclass = "sf"
)
```

```{r}
#Create object state_lookup with columns area and country from object states
state_lookup <- states %>%
  st_drop_geometry() %>%
  transmute(
    area = name,
    country = admin
  ) %>%
  distinct()
```

```{r}
#Create separate table for USA because specified areas are usually there
usa_state_lookup <- state_lookup %>%
  filter(country == "United States of America")
```

```{r}
#Separate the countries depending on the type of eclipse after which they are listed using |
eclipse_areas <- eclipse_data %>%
  select(Date, `Geographical_area`) %>%
  mutate(
    `Geographical_area` = str_replace_all(
      `Geographical_area`,
      "(Total|Annular|Hybrid|Partial):",
      "|\\1:"
    )
  )
```

```{r}
#Separate types from the same date into different rows
eclipse_areas <- eclipse_areas %>%
  separate_rows(
    `Geographical_area`,
    sep = "\\|"
  ) %>%
  filter(`Geographical_area` != "")
```

```{r}
#Separate eclipse type and area into two columns
eclipse_areas <- eclipse_areas %>%
  mutate(
    eclipse_type = str_extract(
      `Geographical_area`,
      "^(Total|Annular|Hybrid|Partial)"
    ),
    area = str_remove(
      `Geographical_area`,
      "^(Total|Annular|Hybrid|Partial):\\s*"
    )
  )
```

```{r}
#Keep only Total and Annular eclipses
eclipse_areas <- eclipse_areas %>%
  filter(eclipse_type == "Total" | eclipse_type == "Annular")
```


```{r}
# Put each country into a different row

# Countries that contain " and " but should NOT be split
and_exceptions <- c(
  "Bosnia and Herzegovina",
  "Antigua and Barbuda",
  "Sao Tome and Principe",
  "Saint Kitts and Nevis",
  "Saint Vincent and the Grenadines",
  "Trinidad and Tobago",
  "Andaman and Nicobar Islands",
  "Turks and Caicos Islands"
)

NSEW_exceptions <- c(
  "Central African Republic",
  "North Carolina",
  "North Dakota",
  "North Pole",
  "North Korea",
  "North Macedonia",
  "Northern Cyprus",
  "Northern Mariana Islands",
  "Northern Territory",
  "Northwest Territories",
  "South Africa",
  "South Australia",
  "South Carolina",
  "South Dakota",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Southeastern Polynesia",
  "Western Java",
  "Western Sahara"
)

eclipse_areas <- eclipse_areas %>%
  # Temporarily protect "and" exceptions
  mutate(
    area = purrr::reduce(
      and_exceptions,
      ~ str_replace_all(
        .x,
        fixed(.y),
        str_replace_all(.y, " and ", "___AND___")
      ),
      .init = area
    )
  ) %>%
  
  # Treat "and" as a separator
  mutate(
    area = str_replace_all(
      area,
      "\\s+and\\s+",
      ", "
    )
  ) %>%
  
  # Split into rows
  separate_rows(
    area,
    sep = ",\\s*"
  ) %>%
  
  # Restore "and"
  mutate(
    area = str_replace_all(
      area,
      "___AND___",
      " and "
    )
  ) %>%
  
  # Remove leading/trailing whitespace
  mutate(
    area = str_trim(area)
  ) %>%

  #Deal separately with Borneo and Southeastern Polynesia because it spans three countries
  mutate(
  area = if_else(
    area == "Borneo",
    "Indonesia, Malaysia, Brunei",
    area
  )
) %>%

  mutate(
  area = if_else(
    area == "Southeastern Polynesia",
    "French Polynesia, Easter Island, Pitcairn Islands",
    area
  )
) %>%

# Split those multi-country areas into separate rows
separate_rows(
  area,
  sep = ",\\s*"
) %>%
  
  # Standardize country/state names
  mutate(
    area = recode(
      area,
      "Cape Verde" = "Cabo Verde",
      "Czech Republic" = "Czechia",
      "East Timor" = "Timor-Leste",
      "Eswatini" = "eSwatini",
      "Andaman and Nicobar Islands" = "Andaman and Nicobar",
      "the Northern Mariana Islands" = "Northern Mariana Islands",
      "Yucatán Peninsula" = "Yucatán",
      "French Guiana" = "Guyane française",
      "Maine Eastern Canada" = "Eastern Canada",
      "Prince Edward Islands" = "Prince Edward Island",
      "northeastern Scotland" = "United Kingdom",
      "Russian Far East" = "Eastern Russia",
      "Southern Primorsky Krai of Russia" = "Primor'ye",
      "Kayangel Atoll" = "Kayangel",
      "Namibian Panhandle" = "Caprivi",
      "Tuamotu Archipelago" = "Tuamotu-Gambier",
      "Western Wilkes Land" = "Antarctica",
      "Wilkes Land" = "Antarctica",
      "Northern and Eastern Russia" = "Russia",
      "Western and Central Canada" = "Canada",
      "Eastern Canary Islands" = "Spain",
      "Canary Islands" = "Spain"
    )
  ) %>%
  
  # Remove NSEW descriptors except for specified exceptions
  mutate(
    area = if_else(
      area %in% NSEW_exceptions,
      area,
      str_remove(
        area,
        regex(
          "^(northern|north|southern|south|eastern|east|western|west|northeastern|northeast|northwestern|northwest|southeastern|southwestern|central)\\s+",
          ignore_case = TRUE
        )
      )
    )
  )
```


```{r}
eclipse_country_info <- eclipse_areas %>%
  left_join(
    country_lookup %>%
      select(country) %>%
      mutate(area = country),
    by = "area"
  ) %>%
  rename(country_direct = country) %>%
  
  left_join(
    usa_state_lookup %>%
      select(area, country) %>%
      rename(country_usa_state = country),
    by = "area"
  ) %>%

  left_join(
    state_lookup %>%
      select(area, country) %>%
      rename(country_state = country),
    by = "area"
  ) %>%
  
  mutate(
    country = coalesce(country_direct, country_usa_state, country_state)
  ) %>%
  
  select(-country_direct, -country_usa_state, -country_state)
```

```{r}
#Manually set problematic names
problem_area_to_country <- c(
  "Annobón Natural Reserve" = "Equatorial Guinea",
  "Bounty Islands" = "New Zealand",
  "Chatham Island" = "New Zealand",
  "Cocos Islands" = "Australia",
  "Crozet Islands" = "France",
  "Easter Island" = "Chile",
  "Kerguelen Islands" = "France",
  "Louisiade Archipelago" = "Papua New Guinea",
  "Nanpō Islands" = "Japan",
  "Republic of the Congo" = "Republic of the Congo",
  "Réunion" = "France",
  "Ryukyu Islands" = "Japan",
  "Stewart Island" = "New Zealand",
  "Sumatra" = "Indonesia",
  "Tibet" = "China",
  "Western Java" = "Indonesia"
)

eclipse_country_info <- eclipse_country_info %>%
  mutate(
    country = coalesce(
      country,
      unname(problem_area_to_country[area])
    )
  )
```

```{r}
problematic_names <- eclipse_country_info %>%
  filter(is.na(country))

sort(unique(problematic_names$area))
```
